# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba1fa5e01f13a1474f6a97f1a4ac863b0f5d44383294eb28f0112be2821aa2cfa37ea9d95d5d35c0c62f037cab985bb4e7886aa730442af132e24280795895a2

test:
  secret_key_base: 28d8275fca43a8861a056d3ae32dbc7ec9bbce5abf563ef2ac7c58e474f7f7f519c034c9b3602281f3794990a9230c3adb5c006996746fa1e864dda4306807bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ad6154ad152ecc3e22045cc2147e0849b42f0ded9641cc180b220e5c3dcbee79372f40199e98263e4154bb1bbb8fc0e9ed55fcefe1349fadbf253ab7ebc2831a
#<%= ENV["SECRET_KEY_BASE"] %>
